parameters:
    fullspeed_csv_serializer.serialization_visitor.class: Fullspeed\CsvSerializerBundle\Serializer\Visitor\CsvSerializationVisitor
    fullspeed_csv_serializer.csv_header_factory.translation.class: Fullspeed\CsvSerializerBundle\Serializer\TranslationalCsvHeaderFactory
    fullspeed_csv_serializer.exporter_factory.class:
        Fullspeed\CsvSerializerBundle\Csv\ExporterFactory
services:
    fullspeed_csv_serializer.serialization_visitor.csv:
        class: "%fullspeed_csv_serializer.serialization_visitor.class%"
        arguments:
            - '@jms_serializer.naming_strategy'
            - '@fullspeed_csv_serializer.csv_header_factory.translation'
            - '@fullspeed_csv_serializer.exporter_factory'
            - '%kernel.cache_dir%'
        tags:
            -  { name: jms_serializer.serialization_visitor, format: csv }

    fullspeed_csv_serializer.csv_header_factory.translation:
        class: '%fullspeed_csv_serializer.csv_header_factory.translation.class%'
        arguments:
            - '@translator'
            - '@jms_serializer.metadata_factory'
        public: false
    fullspeed_csv_serializer.exporter_factory:
        class: '%fullspeed_csv_serializer.exporter_factory.class%'
        public: false